In [1]:
%load_ext watermark
%watermark -v -p numpy,sklearn,scipy,matplotlib,tensorflow

CPython 3.6.6
IPython 6.4.0

numpy 1.14.5
sklearn 0.19.1
scipy 1.1.0
matplotlib 2.2.2
tensorflow 1.9.0


***12장 – 분산 텐서플로***

목적
- 대규모 NN 을 여러 장치에 병렬 / 분산 실행하여 수행 시간을 절약한다.

Tensorflow 분산 처리의 장점
- 계산 그래프의 여러 장치 / 머신 분할방법 제어 가능
- 다양한 방식의 연산 병렬화 및 동기화 가능

병렬 수행의 실사례
- 신경망 병렬 수행
- 모델 세밀 튜닝을 위해 큰 하이퍼파라미터 공간을 탐색
- 대규모 NN 의 앙상블 수행

**12.1 단일 머신의 다중 장치**

- 단일 머신에 GPU 추가
- 다중 머신의 경우 네트워크 비용으로 인해 더 비효율적일 수 있음

*12.1.1 설치*

- 그래픽 카드 호환성 확인 : https://developer.nvidia.com/cuda-gpus
- CUDA : gpu 를 통한 명시적 computing 을 가능하게 하는 library
- cuDNN : DNN 을 위한 기초적 GPU 가속 library
-- activation function, normalize, forward / back propagation, pooling 등
- CUDA, cuDNN 바이너리 다운로드시 nvidia 개발자 계정이 필요 (https://developer.nvidia.com/)

* 본 실습에서는 gcp 를 활용

In [ ]:
!nvidia-smi

- pyenv, anaconda 등 가상 환경을 사용하고 잇다면 적절한 환경으로 활성화

# 설정

파이썬 2와 3을 모두 지원합니다. 공통 모듈을 임포트하고 맷플롯립 그림이 노트북 안에 포함되도록 설정하고 생성한 그림을 저장하기 위한 함수를 준비합니다:

In [2]:
# 파이썬 2와 파이썬 3 지원
from __future__ import division, print_function, unicode_literals

# 공통
import numpy as np
import os

# 일관된 출력을 위해 유사난수 초기화
def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

# 맷플롯립 설정
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

# 그림을 저장할 폴더
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "distributed"

def save_fig(fig_id, tight_layout=True):
    path = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID, fig_id + ".png")
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format='png', dpi=300)

# 로컬 서버

In [3]:
import tensorflow as tf

In [4]:
c = tf.constant("Hello distributed TensorFlow!")
server = tf.train.Server.create_local_server()

In [5]:
with tf.Session(server.target) as sess:
    print(sess.run(c))

b'Hello distributed TensorFlow!'


- gpu 초기화 및 정보 로그가 나온다면 성공

*12.1.2 GPU RAM 관리*

- 단일 GPU 에 여러 프로그램 수행시 경우에 따라 OOM 발생할 수 있음

1. 별도 GPU 에 각각 수행

In [ ]:
#CUDA_VISIBLE_DEVICES=0,1 python3 code.py - 복수 device ID 지정시 multi gpu 로 구동되는지 확인
#CUDA_VISIBLE_DEVICES="" 의 경우 CPU 로 수행됨

# https://stackoverflow.com/questions/37893755/tensorflow-set-cuda-visible-devices-within-jupyter
# http://dongjinlee.tistory.com/entry/%EC%84%A0%ED%83%9D%ED%95%9C-GPU%EC%97%90%EB%A7%8C-%EB%A9%94%EB%AA%A8%EB%A6%AC-%ED%95%A0%EB%8B%B9%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="0"
# do some tensor

2. GPU 메모리 일부만을 사용하도록 강제

In [ ]:
config = tf.configProto();
config.gpu_options.per_process_gpu_memory_fraction = 0.4
session = tf.session(config=config)

In [ ]:
!nvidia-smi

3. 필요할 때 메모리를 확장 할당하는 옵션 활용
- 비활용 메모리 반납에 시간이 소요되므로(memory fragmentation 을 피하기 위해) 효용성이 낮음

In [ ]:
config = tf.configProto();
config.gpu_options.allow_growth = True
session = tf.session(config=config)

*12.1.3 장치에 연산 배치하기*

dynamic placer
- 사용자 지정 배치 규칙에 비해 좋은 효율성을 보이고 있지 않다고 함.
- G사 내부용으로 현재 오픈소스화 되어 잇지 않음.

1. simple placer
- computation graph 수행시 device 에 배치되지 않는 node 를 평가할 때 사용

분배 규칙
- node 가 이미 배치되어 있는 장비는 해당 node를 그대로 둠
- 사용자가 node 를 어떤 장치에 할당햇다면 placer 가 node 를 배치
- GPU #0 이 기본, GPU 가 소진되면 CPU 로 전환

2. 배치 로깅
- placer 가 node 를 배치할 시점에 메세지를 기록하는 옵션
- TODO : 출력되는 log 에 대한 부연 설명

In [ ]:
with tf.device("/cpu:0"):
    a = tf.Variable(3.0)
    b = tf.constant(4.0)

c = a * b

config = tf.ConfigProto()
config.log_device_placement = True
session = tf.session(config=config)

In [ ]:
a.initializer.run(session=sess)

In [ ]:
sess.run(c)

3. 동적 배치 함수

- tf.device 파라미터로 함수를 넣을 수 있음
- 실무에서 자주 사용 되나요?

In [ ]:
def variables_on_cpu(op):
    if(op.type == "Variable"):
        return "/cpu:0"
    else:
        return "/gpu:0"

with tf.device(variables_on_cpu):
    a = tf.Variable(3.0)
    b = tf.constant(4.0)
    c = a * b

4. 연산과 커널

- CPU, GPU 장치별로 지원가능한 연산이 구분되어 잇음
- 커널 : 장치에 맞는 구현
- 예) integer Variable 은 GPU 에서 지원하지 않음 - 효율성 문제로 강제 미지원
- 하시 예시의 경우, dtype=tf.float32 로 명시하지 않으면 숫자 notation 을 통해 정수로 임의판단함

In [ ]:
with tf.device("/gpu:0"):
    a = tf.Variable(3) 
    
session.run(i.initializer) # error

5. 간접 배치

- 해당 커널이 없는 device 에 할당된 연산을, 해당 커널을 가진 임의 device 에 할당하는 옵션
- 묵시적 할당이라 프로그래머 예측을 벗어나는 위험이 잇어보이는데...
- GPU 가 없을때 CPU 가 지원안하는 커널인 연산을 입력하면? (그런게 잇나?)

In [ ]:
with tf.device("/gpu:0"):
    a = tf.Variable(3)
    
config = tf.ConfigProto()
config.allow_soft_placement = True
session = tf.session(config=config)
session.run(i.initializer) # /cpu:0

*12.1.4 병렬 실행*

CPU
1) queueing
- nn graph 실행시, 먼저 평가할 연산을 찾은 뒤 관련 연산들의 의존도를 측정
- 의존성이 전혀 없는 node 들을 할당된 장치의 evaluation queue 에 추가
- 하나의 연산이 평가되면 다른 모든 연산의 dependency counter 가 감소
- 그 후 dependency counter 가 0 이 되는 연산이 추가로 장치의 evaluation queue 에 추가
- 필요한 모든 Node 가 평가되면 output 을 return
2) pooling
- cpu 의 evaluation queue 에 있는 연산은 inter-op thread pool 로 이동
- 각 상황에 맞도록 병렬 처리  
-- multi-core hardware 를 이용
-- multithread cpu 커널 
--- 여러개의 부분연산으로 분리하여 다른 evaluation queue 에 배치
--- 상기 evaluation queue 에 배치된 연산은 (모든 multithread cpu 커널이 공유하는)intra-op thread pool 로 이동

- inter / intra-op thread pool 의 thread 수는 옵션으로 조정가능 - default 0 (모든 코어 사용)
-- 현재 CPU 특정 코어 지정이 불가하기 때문에, 옵션값을 CPU 코어 수 보다 적에 부여해야함

GPU
- GPU 상의 evaluation queue 연산들은 순서대로 평가됨
- 대다수의 연산에 대한 CUDA / cuDNN 기반 multithread GPU 커널 존재


* 그림 12-5 삽입 및 관련 설명 추가



*12.1.5 제어 의존성*

- 의존 연산이 모두 수행되엇음에도, 효율을 위해 evaluation 을 가급적 delay 할 경우
-- 다량의 메모리 점유, 다수의 external I/O 발생 등
- 다른 연산을 병렬 처리 하며 순차적 실행




In [ ]:
a = tf.constant(1.0)
b = a + 2.0

with tf.control_dependencies([a,b]):
    x = tf.constant(3.0)
    y = tf.constant(4.0)
    
z = x + y # z 도 a, b 의 evaluation 을 기다리는 의존성이 발생

**12.2 다중 머신의 다중 장치**

- task : 하나 이상의 텐서플로 서버로 구성
- job : 각기 이름이 부여된 task group
- cluster : task 라고 불리는 하나 이상의 텐서플로 서버로 구성


* 그림 12-6 추가 및 설명

# 클러스터

In [6]:
cluster_spec = tf.train.ClusterSpec({
    "ps": [
        "127.0.0.1:2221",  # /job:ps/task:0
        "127.0.0.1:2222",  # /job:ps/task:1
    ],
    "worker": [
        "127.0.0.1:2223",  # /job:worker/task:0 # 외부 장비 ip 로 교체
        "127.0.0.1:2224",  # /job:worker/task:1
        "127.0.0.1:2225",  # /job:worker/task:2
    ]})

In [7]:
# 동일 머신에서 여러 task 수행은 가능하나 비추천. 각 GPU RAM 점유를 수동으로 조정해줘야함
task_ps0 = tf.train.Server(cluster_spec, job_name="ps", task_index=0)
task_ps1 = tf.train.Server(cluster_spec, job_name="ps", task_index=1)
task_worker0 = tf.train.Server(cluster_spec, job_name="worker", task_index=0)
task_worker1 = tf.train.Server(cluster_spec, job_name="worker", task_index=1)
task_worker2 = tf.train.Server(cluster_spec, job_name="worker", task_index=2)

# cluster task 설정 시 CUDA_VISIBLE_DEVICES 를 구분지어 설정할 수 있는가?
#server.join() ??

*12.2.1 세션 열기*

- 모든 task 가 시작되면 특정 머신의 프로세스의 클라이언트에서 다른 모든 서버에 대해 세션을 열 수 있음
- 하기 예시에서, 

In [ ]:
a = tf.constant(1.0)
b = a + 2
c = a * 3

# 해당 원격 텐서플로 서버에 대한 세션을 오픈, c 를 evaluate 하라는 명령을 전달
# 해당 외부 장비의 기본장치(GPU) 에 배치 후 수행, 결과 반환
with tf.Session("grpc://127.0.0.1:2223") as sess: # 외부 장비 ip 로 교체
    print(c.eval())

In [ ]:
*12.2.2 마스터와 워커 서비스*

- Client / Server 는 gRPC 로 통신함
-- 적절한 통신 포트를 방화벽에서 열어주어야 함
- 텐서플로 서버는 기본적으로 마스터, 워커 서비스를 제공함
-- 마스터 : 클라이언트가 세션을 열고 그래플르 실행할 수 잇게 해줌
-- 워커 : 하나의 서버에서 graph 실행을 담당하는 RPC 서비스
    
- 유연성 제공
- 1 Client 가 n Server 에 접속하는 각각 session 오픈 가능
- task 마다 1 client 실행
- 1 client 로 여러 task 제어



*12.2.3 여러 태스크에 연산 할당하기*

- job 이름, task 번호, 장치 유형/번호 지정하여 연산 할당 가능
- 장치 유형/번호가 지정되지 않으면 해당 task 의 기본 장치 사용


# 여러 디바이스와 서버에 연산을 할당하기

In [8]:
reset_graph()

with tf.device("/job:ps"):
    a = tf.Variable(1.0, name="a")

with tf.device("/job:worker"):
    b = a + 2

with tf.device("/job:worker/task:1"):
    c = a + b
    
with tf.device("/job:ps/task:1/cpu:0"):
    d = a + c

In [9]:
with tf.Session("grpc://127.0.0.1:2221") as sess:
    sess.run(a.initializer)
    print(c.eval())

4.0


*12.2.4 여러 대의 파라미터 서버에 변수를 나누어 분산하기*

- 다량의 파라미터가 있는 대규모 모델의 경우, 서버 한 대로 IO가 몰리지 않게 여러 서버에 분산해둠
- 별도 명시설정없이 모든 task 에 round-robin 할당해주는 방법 제공
- 대체로 파라미터 서버는 파라미터 저장 / 송수신 용도로 사용되고 무거운 연산을 수행하지 않게 구성

In [10]:
reset_graph()

with tf.device(tf.train.replica_device_setter( # cluster=cluster_spec 처럼 클러스터 명세를 전달해도 ps_tasks 를 찾아서 이용함
        ps_tasks=2,
        ps_device="/job:ps",
        worker_device="/job:worker")):
    v1 = tf.Variable(1.0, name="v1")  # /job:ps/task:0 (defaults to /cpu:0) 에 할당
    v2 = tf.Variable(2.0, name="v2")  # /job:ps/task:1 (defaults to /cpu:0) 에 할당
    v3 = tf.Variable(3.0, name="v3")  # /job:ps/task:0 (defaults to /cpu:0) 에 할당
    s = v1 + v2            # /job:worker (defaults to task:0/cpu:0) 에 할당
    with tf.device("/task:1"):
        p1 = 2 * s         # /job:worker/task:1 (defaults to /cpu:0) 에 할당
        with tf.device("/cpu:0"):
            p2 = 3 * s     # /job:worker/task:1/cpu:0 에 할당

config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session("grpc://127.0.0.1:2221", config=config) as sess:
    v1.initializer.run()

*12.2.5 리소스 컨테이너를 사용해 여러 세션에서 상태 공유하기*

TBD

# 리더 (Reader) - 예전 방법

In [11]:
reset_graph()

default1 = tf.constant([5.])
default2 = tf.constant([6])
default3 = tf.constant([7])
dec = tf.decode_csv(tf.constant("1.,,44"),
                    record_defaults=[default1, default2, default3])
with tf.Session() as sess:
    print(sess.run(dec))

[1.0, 6, 44]


In [12]:
reset_graph()

test_csv = open("my_test.csv", "w")
test_csv.write("x1, x2 , target\n")
test_csv.write("1.,, 0\n")
test_csv.write("4., 5. , 1\n")
test_csv.write("7., 8. , 0\n")
test_csv.close()

filename_queue = tf.FIFOQueue(capacity=10, dtypes=[tf.string], shapes=[()])
filename = tf.placeholder(tf.string)
enqueue_filename = filename_queue.enqueue([filename])
close_filename_queue = filename_queue.close()

reader = tf.TextLineReader(skip_header_lines=1)
key, value = reader.read(filename_queue)

x1, x2, target = tf.decode_csv(value, record_defaults=[[-1.], [-1.], [-1]])
features = tf.stack([x1, x2])

instance_queue = tf.RandomShuffleQueue(
    capacity=10, min_after_dequeue=2,
    dtypes=[tf.float32, tf.int32], shapes=[[2],[]],
    name="instance_q", shared_name="shared_instance_q")
enqueue_instance = instance_queue.enqueue([features, target])
close_instance_queue = instance_queue.close()

minibatch_instances, minibatch_targets = instance_queue.dequeue_up_to(2)

with tf.Session() as sess:
    sess.run(enqueue_filename, feed_dict={filename: "my_test.csv"})
    sess.run(close_filename_queue)
    try:
        while True:
            sess.run(enqueue_instance)
    except tf.errors.OutOfRangeError as ex:
        print("더 이상 읽을 파일이 없습니다")
    sess.run(close_instance_queue)
    try:
        while True:
            print(sess.run([minibatch_instances, minibatch_targets]))
    except tf.errors.OutOfRangeError as ex:
        print("더 이상 훈련 샘플이 없습니다")

더 이상 읽을 파일이 없습니다
[array([[ 4.,  5.],
       [ 1., -1.]], dtype=float32), array([1, 0], dtype=int32)]
[array([[7., 8.]], dtype=float32), array([0], dtype=int32)]
더 이상 훈련 샘플이 없습니다


In [13]:
#coord = tf.train.Coordinator()
#threads = tf.train.start_queue_runners(coord=coord)
#filename_queue = tf.train.string_input_producer(["test.csv"])
#coord.request_stop()
#coord.join(threads)

# QueueRunner와 Coordinator

In [14]:
reset_graph()

filename_queue = tf.FIFOQueue(capacity=10, dtypes=[tf.string], shapes=[()])
filename = tf.placeholder(tf.string)
enqueue_filename = filename_queue.enqueue([filename])
close_filename_queue = filename_queue.close()

reader = tf.TextLineReader(skip_header_lines=1)
key, value = reader.read(filename_queue)

x1, x2, target = tf.decode_csv(value, record_defaults=[[-1.], [-1.], [-1]])
features = tf.stack([x1, x2])

instance_queue = tf.RandomShuffleQueue(
    capacity=10, min_after_dequeue=2,
    dtypes=[tf.float32, tf.int32], shapes=[[2],[]],
    name="instance_q", shared_name="shared_instance_q")
enqueue_instance = instance_queue.enqueue([features, target])
close_instance_queue = instance_queue.close()

minibatch_instances, minibatch_targets = instance_queue.dequeue_up_to(2)

n_threads = 5
queue_runner = tf.train.QueueRunner(instance_queue, [enqueue_instance] * n_threads)
coord = tf.train.Coordinator()

with tf.Session() as sess:
    sess.run(enqueue_filename, feed_dict={filename: "my_test.csv"})
    sess.run(close_filename_queue)
    enqueue_threads = queue_runner.create_threads(sess, coord=coord, start=True)
    try:
        while True:
            print(sess.run([minibatch_instances, minibatch_targets]))
    except tf.errors.OutOfRangeError as ex:
        print("더 이상 훈련 샘플이 없습니다")

[array([[ 7.,  8.],
       [ 1., -1.]], dtype=float32), array([0, 0], dtype=int32)]
[array([[4., 5.]], dtype=float32), array([1], dtype=int32)]
더 이상 훈련 샘플이 없습니다


In [15]:
reset_graph()

def read_and_push_instance(filename_queue, instance_queue):
    reader = tf.TextLineReader(skip_header_lines=1)
    key, value = reader.read(filename_queue)
    x1, x2, target = tf.decode_csv(value, record_defaults=[[-1.], [-1.], [-1]])
    features = tf.stack([x1, x2])
    enqueue_instance = instance_queue.enqueue([features, target])
    return enqueue_instance

filename_queue = tf.FIFOQueue(capacity=10, dtypes=[tf.string], shapes=[()])
filename = tf.placeholder(tf.string)
enqueue_filename = filename_queue.enqueue([filename])
close_filename_queue = filename_queue.close()

instance_queue = tf.RandomShuffleQueue(
    capacity=10, min_after_dequeue=2,
    dtypes=[tf.float32, tf.int32], shapes=[[2],[]],
    name="instance_q", shared_name="shared_instance_q")

minibatch_instances, minibatch_targets = instance_queue.dequeue_up_to(2)

read_and_enqueue_ops = [read_and_push_instance(filename_queue, instance_queue) for i in range(5)]
queue_runner = tf.train.QueueRunner(instance_queue, read_and_enqueue_ops)

with tf.Session() as sess:
    sess.run(enqueue_filename, feed_dict={filename: "my_test.csv"})
    sess.run(close_filename_queue)
    coord = tf.train.Coordinator()
    enqueue_threads = queue_runner.create_threads(sess, coord=coord, start=True)
    try:
        while True:
            print(sess.run([minibatch_instances, minibatch_targets]))
    except tf.errors.OutOfRangeError as ex:
        print("더 이상 훈련 샘플이 없습니다")

[array([[ 4.,  5.],
       [ 1., -1.]], dtype=float32), array([1, 0], dtype=int32)]
[array([[7., 8.]], dtype=float32), array([0], dtype=int32)]
더 이상 훈련 샘플이 없습니다


# 타임아웃 지정하기

In [16]:
reset_graph()

q = tf.FIFOQueue(capacity=10, dtypes=[tf.float32], shapes=[()])
v = tf.placeholder(tf.float32)
enqueue = q.enqueue([v])
dequeue = q.dequeue()
output = dequeue + 1

config = tf.ConfigProto()
config.operation_timeout_in_ms = 1000

with tf.Session(config=config) as sess:
    sess.run(enqueue, feed_dict={v: 1.0})
    sess.run(enqueue, feed_dict={v: 2.0})
    sess.run(enqueue, feed_dict={v: 3.0})
    print(sess.run(output))
    print(sess.run(output, feed_dict={dequeue: 5}))
    print(sess.run(output))
    print(sess.run(output))
    try:
        print(sess.run(output))
    except tf.errors.DeadlineExceededError as ex:
        print("dequeue 타임 아웃")

2.0
6.0
3.0
4.0
dequeue 타임 아웃


# Data API

텐서플로 1.4에서 소개된 Data API를 사용하면 손쉽게 데이터를 효율적으로 읽을 수 있습니다.

In [17]:
tf.reset_default_graph()

0에서 9까지 정수를 세 번 반복한 간단한 데이터셋을 일곱 개씩 배치로 만들어 시작해 보죠:

In [18]:
dataset = tf.data.Dataset.from_tensor_slices(np.arange(10))
dataset = dataset.repeat(3).batch(7)

첫 번째 줄은 0에서 9까지 정수를 담은 데이터셋을 만듭니다. 두 번째 줄은 이 데이터셋의 원소를 세 번 반복하고 일곱 개씩 담은 새로운 데이터셋을 만듭니다. 위에서 볼 수 있듯이 원본 데이터셋에서 여러 변환 메서드를 연결하여 호출하여 적용했습니다.

그다음, 데이터셋을 한 번 순회하는 원-샷-이터레이터(one-shot-iterator)를 만들고, 다음 원소를 지칭하는 텐서를 얻기 위해 `get_next()` 메서드를 호출합니다.

In [19]:
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

`next_element`를 반복적으로 평가해서 데이터셋을 순회해 보죠. 원소가 별로 없기 때문에 `OutOfRangeError`가 발생합니다:

In [20]:
with tf.Session() as sess:
    try:
        while True:
            print(next_element.eval())
    except tf.errors.OutOfRangeError:
        print("완료")

[0 1 2 3 4 5 6]
[7 8 9 0 1 2 3]
[4 5 6 7 8 9 0]
[1 2 3 4 5 6 7]
[8 9]
완료


좋네요! 잘 작동합니다.

늘 그렇듯이 텐서는 그래프를 실행(`sess.run()`)할 때마다 한 번만 평가된다는 것을 기억하세요. `next_element`에 의존하는 텐서를 여러개 평가하더라도 한 번만 평가됩니다. 또한 `next_element`를 동시에 두 번 실행해도 마찬가지입니다:

In [21]:
with tf.Session() as sess:
    try:
        while True:
            print(sess.run([next_element, next_element]))
    except tf.errors.OutOfRangeError:
        print("완료")

[array([0, 1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4, 5, 6])]
[array([7, 8, 9, 0, 1, 2, 3]), array([7, 8, 9, 0, 1, 2, 3])]
[array([4, 5, 6, 7, 8, 9, 0]), array([4, 5, 6, 7, 8, 9, 0])]
[array([1, 2, 3, 4, 5, 6, 7]), array([1, 2, 3, 4, 5, 6, 7])]
[array([8, 9]), array([8, 9])]
완료


`interleave()` 메서드는 강력하지만 처음에는 이해하기 좀 어렵습니다. 예제를 통해 이해하는 것이 가장 좋습니다:

In [22]:
tf.reset_default_graph()

In [23]:
dataset = tf.data.Dataset.from_tensor_slices(np.arange(10))
dataset = dataset.repeat(3).batch(7)
dataset = dataset.interleave(
    lambda v: tf.data.Dataset.from_tensor_slices(v),
    cycle_length=3,
    block_length=2)
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

In [24]:
with tf.Session() as sess:
    try:
        while True:
            print(next_element.eval(), end=",")
    except tf.errors.OutOfRangeError:
        print("완료")

0,1,7,8,4,5,2,3,9,0,6,7,4,5,1,2,8,9,6,3,0,1,2,8,9,3,4,5,6,7,완료


`cycle_length=3`이므로 새로운 데이터셋은 이전 데이터셋에서 세 개의 원소를 추출합니다. 즉 `[0,1,2,3,4,5,6]`, `[7,8,9,0,1,2,3]`, `[4,5,6,7,8,9,0]` 입니다. 그다음 원소마다 하나의 데이터셋을 만들기 위해 람다(lambda) 함수를 호출합니다. `Dataset.from_tensor_slices()`를 사용했기 때문에 각 데이터셋은 차례대로 원소를 반환합니다. 다음 이 세 개의 데이터셋에서 각각 두 개의 아이템(`block_length=2`이므로)을 추출합니다. 세 개의 데이터셋의 아이템이 모두 소진될 때까지 반복됩니다. 즉 0,1 (첫 번째에서), 7,8 (두 번째에서), 4,5 (세 번째에서), 2,3 (첫 번째에서), 9,0 (두 번째에서) 등과 같은 식으로 8,9 (세 번째에서), 6 (첫 번째에서), 3 (두 번째에서), 0 (세 번째에서)까지 진행됩니다. 그다음에 원본 데이터셋에서 다음 번 세 개의 원소를 추출하려고 합니다. 하지만 두 개만 남아 있습니다. `[1,2,3,4,5,6,7]`와 `[8,9]` 입니다. 다시 이 원소로부터 데이터셋을 만들고 이 데이텃세의 아이템이 모두 소진될 때까지 두 개의 아이템을 추출합니다. 1,2 (첫 번째에서), 8,9 (두 번째에서), 3,4 (첫 번째에서), 5,6 (첫 번째에서), 7 (첫 번째에서)가 됩니다. 배열의 길이가 다르기 때문에 마지막에는 교대로 배치되지 않았습니다.

# 리더 (Reader) - 새로운 방법

`from_tensor_slices()`나 `from_tensor()`를 기반으로 한 원본 데이터셋을 사용하는 대신 리더 데이터셋을 사용할 수 있습니다. 복잡한 일들을 대부분 대신 처리해 줍니다(예를 들면, 스레드):

In [25]:
tf.reset_default_graph()

In [26]:
filenames = ["my_test.csv"]

In [27]:
dataset = tf.data.TextLineDataset(filenames)

각 줄을 어떻게 디코드해야 하는지는 알려 주어야 합니다:

In [28]:
def decode_csv_line(line):
    x1, x2, y = tf.decode_csv(
        line, record_defaults=[[-1.], [-1.], [-1.]])
    X = tf.stack([x1, x2])
    return X, y

그다음, 이 디코딩 함수를 `map()`을 사용하여 데이터셋에 있는 각 원소에 적용할 수 있습니다:

In [29]:
dataset = dataset.skip(1).map(decode_csv_line)

마지막으로 원-샷-이터레이터를 만들어 보죠:

In [30]:
it = dataset.make_one_shot_iterator()
X, y = it.get_next()

In [31]:
with tf.Session() as sess:
    try:
        while True:
            X_val, y_val = sess.run([X, y])
            print(X_val, y_val)
    except tf.errors.OutOfRangeError as ex:
        print("완료")

[ 1. -1.] 0.0
[4. 5.] 1.0
[7. 8.] 0.0
완료


# 연습문제 해답

**Coming soon**